name: Lint

on:
  push:
    branches:
      - f38
  pull_request:
    branches:
      - f38
  merge_group:
    branches:
      - f38
jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/terrapkg/builder:f38
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Lint spec files
        run: rpmlint $(find anda -type f -name "*.spec" -type f)
